### ISSUE TITLE
complile stops with: [all-recursive] Error 1

### ISSUE THREAD

**Issue by shiraz-shah** [arumugamlab/msamtools#3]
Can't compile the release nor the checked out source. make stops with following error:

make[1]: Leaving directory '/home/shiraz/apps/msamtools/deps'
Makefile:548: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by microbiomix** [comment]
Can you please provide more details? Like hardware/OS/software configs, full compilation log?

**Comment by shiraz-shah** [comment]
Hey Mani,
I get this on our Ubuntu 18.04 LTS server.

I also tried it just now on a fresh install of ubuntu 16.04, and get the same error (complete log attached).
[log.txt](https://github.com/arumugamlab/msamtools/files/4303019/log.txt)

**Comment by microbiomix** [comment]
Hi Shiraz,

As the log file says, building of the dependency "samtools" because you are missing curses library development version. I will update this info in the installation requirements. For now, can you please install the library and then try again?

Best,
Mani

**Comment by shiraz-shah** [comment]
It worked. Thanks!

Can't wait to try this tool!

**Comment by microbiomix** [comment]
Great! I have updated install instructions with system requirements.
