### ISSUE TITLE
input through stdin doesn't work

### ISSUE THREAD

**Issue by shiraz-shah** [arumugamlab/msamtools#4]
Hey Mani,
I'm trying to get it to input from stdin but it doesn't seem to work:

```
msamtools filter -b -u -l 80 -p 95 -z 80 --besthit test.bam | msamtools profile --multi=proportional --label=test -o /dev/stdout -
test.bam
-
[E::hts_hopen] Failed to open file -
[E::hts_open_format] Failed to open file -
Fatal Error: Cannot open - for reading
```

Any ideas?

**Comment by microbiomix** [comment]
Hi Shiraz,

This was indeed a bug, but was fixed in a recent commit. It is not pushed to a release yet though. Can you please check out the latest version from github and try? That should work properly.

Best,
Mani

**Comment by shiraz-shah** [comment]
Finally got the chance to test this. It seems to work just fine now!

Thanks, Mani.
