### ISSUE TITLE
make sure with the output

### ISSUE THREAD

**Issue by Wanli-HE** [arumugamlab/msamtools#6]
![image](https://user-images.githubusercontent.com/58076352/150513661-89827698-5483-4d69-a30a-3a8a65cf1e42.png)
here is the msamtools coverage command and output, i am not sure yhe 2rd column, is that means how many positions of that contigs are coveraged by reads? if contig1 is 0.99, which means 99% of contig1 position are found had reads mapped.

**Comment by microbiomix** [comment]
Hi,
For example, line 5 shows that `99.987346%` of the genome positions were covered by at least one alignment. And the total sequence coverage (average number of reads per position) is `70.04X`. Does this clarify your confusion?

**Comment by Wanli-HE** [comment]
> Does this clarify your confusion?

yes! thanks
