### ISSUE TITLE
please provide test data

### ISSUE THREAD

**Issue by EricDeveaud** [arumugamlab/msamtools#7]
Hello, 

would you min to provide the bam files used for the tests
```
# Files
small_file="input.uniq.bam"
tiny_file="tiny_aln.bam"
```
and the expected outputs. 

regards

Eric

**Comment by microbiomix** [comment]
Hello,

The testing script you are referring to performs only regression tests and integrity tests. It does not compare outputs with some predefined "truth" but with outputs from the previous stable version. So, it does not make sense to provide "expected outputs".

However, if you are making changes to the code yourself, you can use the tests to make sure nothing else is broken. 

I have added `tiny_aln.bam` to the repository. The other file is over `100MB`, so I would rather not add it here.

Hope this helps!

Best,
Mani

**Comment by EricDeveaud** [comment]
ok thanks for the answer. 

i do not make code modification, I'm just a tech guy that use to run some tests once I've installed a tool.

thanks again

Eric

**Comment by microbiomix** [comment]
PR #22 added a test suite that compares achieved results with expected results. This can be run with `make check`.
